#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# only branches and files git completion
__git_files () {
    _wanted files expl 'local files' _files
}

alias j=fasd_cd

alias chrome='open -a /Applications/Google\ Chrome.app'
